### ISSUE TITLE
Walle-core: action warn: missing field `action` at line 1 column 140

### ISSUE THREAD

**Issue by UlyssesZh** [onebot-walle/walle-q#24]
一运行 walle-q 就被这条警告刷屏了.

**Comment by abrahum** [comment]
你使用的应用端是什么，最好提供应用端的详细配置信息。

你的应用端可能使用的是onebot11协议，walleq仅支持onebot12（~~目前~~

**Comment by UlyssesZh** [comment]
还没有接入应用端的时候就会报.

**Comment by abrahum** [comment]
请提供完整log

**Comment by UlyssesZh** [comment]
> 你的应用端可能使用的是onebot11协议

抱歉, 是我判断失误. 你说的是对的. 应用端是 Koishi.
