### ISSUE TITLE
windows下生成的二维码错位

### ISSUE THREAD

**Issue by axty666** [onebot-walle/walle-q#26]
![Z `4 KY(RFG0T} KIY7W1J](https://user-images.githubusercontent.com/76648930/206189483-1b9384b3-1c44-48f5-8c52-727a4b134c23.png)
或许可能把二维码图片放到程序同目录下（类似于gocqhttp的那种）可能能作为最后一种办法？

**Comment by abrahum** [comment]
解决方案： #25 

会在下个版本增加同时输出图片文件（但还是更建议使用现代化的终端

**Comment by axty666** [comment]
十分感谢

**Comment by axty666** [comment]
找到了一个比较好（可能）的解决办法：
换字体，把字体换成诸如Courier New或者Lucida console这种等宽字体可以缓解二维码错位的问题
