### ISSUE TITLE
应该如何使用get/post发送消息？

### ISSUE THREAD

**Issue by 1486308032** [onebot-walle/walle-q#30]
INFO Walle-core: Starting HTTP server on http://0.0.0.0:5700

url = 'http://ip:5700/send_message'
data = {
    "detail_type": "private",
    "user_id": "qq",
    "message": str(msg)
}
get/post都没有响应

**Comment by abrahum** [comment]
请阅读 [onebot12 标准 HTTP](https://12.onebot.dev/connect/communication/http/)
