### ISSUE TITLE
消息删除事件 和 `reply`消息 的 `message_id` 似乎有问题

### ISSUE THREAD

**Issue by MeetWq** [onebot-walle/walle-q#31]
发送消息 `send_message` 返回的 `message_id` 形如: `"905796188 19103 293367355"`
而 `group_message_delete` 等事件 以及 回复消息 的 `message_id` 形如: `"19103"`

**Comment by abrahum** [comment]
确实存在问题

目前考虑到无数据库运行，所以普通 message_id 需要包含 seq rand time 三个信息

而撤回事件仅能获取到 seq 无法获得别的字段，需要通过数据库查询

会修复该字段在启用数据库时正确返回
