### ISSUE TITLE
问一下，是否还在更新？

### ISSUE THREAD

**Issue by fy0** [onebot-walle/walle-q#34]
因为gocq最近的问题，试图适配ricq，使用walle-q作为协议实现端。
都已经适配完成了……然后发现是ricq 0.1.16，版本时间是22年5月

**Comment by abrahum** [comment]
能正常用为啥要更新（笑

正经回答：当然会继续维护，最近本职工作比较忙，所以更多 feature 的增加工作暂时搁置了，如果遇到已实现功能的问题，欢迎反馈，视问题严重程度，会进行修复。
