### ISSUE TITLE
群邀请 request.group_invited 事件实现与文档不符

### ISSUE THREAD

**Issue by lunzhiPenxil** [onebot-walle/walle-q#37]
![1111](https://user-images.githubusercontent.com/26300331/227120523-dbe32643-5c33-4a73-8ef3-327f852da4cd.png)
如图，文档中提到，该事件的`detail_type`应当为`group_invited`
![2222222](https://user-images.githubusercontent.com/26300331/227120539-f3add4b4-c120-4a11-95c4-53198bf42d17.png)
但我在调试中发现该处实际为`group_invite`。
所以目前想讨论看看准备怎样修改，是修改文档还是修改实现。

**Comment by abrahum** [comment]
感觉 invite 比较合适
