### ISSUE TITLE
调用`get_user_info`接口时出错`missing SummaryCard.RespSummaryCard`

### ISSUE THREAD

**Issue by CMHopeSunshine** [onebot-walle/walle-q#40]
尝试了一下`get_friend_list`接口能正常获取好友列表，但`get_user_info`会报以下错误：
`[Action Failed 34001] ricq错误:failed to decode, missing SummaryCard.RespSummaryCard`
![image](https://user-images.githubusercontent.com/63870437/227882962-db44e85f-4145-47aa-9c04-84cbe4bf302a.png)
在ricq的issue中并未发现相关问题。

另外目前好像只有手表协议+扫码能登录成功，其他会提示`版本过低`，不知是否会更新协议版本呢？
感谢开发者~

**Comment by lunzhiPenxil** [comment]
我这边使用`get_user_info`也遇到了同样的问题。

**Comment by abrahum** [comment]
经测试为手表协议缺乏部分字段导致的该问题，切换其他协议不存在该问题。

目前安卓手机协议和安卓平板协议已更新修复，可以使用密码登录，将尽快发布新版本修改该问题。
